/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        {
          type: 'doc',
          id: 'introduction/quickstart',
          label: 'Quickstart',
        },
        'introduction/screenshots',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        {
          type: 'doc',
          id: 'architecture/components',
          label: 'Components',
        },
        {
          type: 'doc',
          id: 'architecture/envars',
          label: 'Environment Variables',
        },
        {
          type: 'doc',
          id: 'architecture/logger',
          label: 'Logger',
        },
        {
          type: 'doc',
          id: 'architecture/storage',
          label: 'Storage System',
        },
        {
          type: 'doc',
          id: 'architecture/router',
          label: 'Router',
        },
        {
          type: 'doc',
          id: 'architecture/template-engine',
          label: 'Template Engine',
        },
        {
          type: 'doc',
          id: 'architecture/session',
          label: 'Session Manager',
        },
        {
          type: 'doc',
          id: 'architecture/barebones',
          label: 'Barebones App',
        },
      ],
    },
    {
      type: 'category',
      label: 'Plugins',
      items: [
        {
          type: 'doc',
          id: 'plugins/overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'plugins/library',
          label: 'Library',
        },
        {
          type: 'doc',
          id: 'plugins/mvp',
          label: 'Your First Plugin (MVP)',
        },
        {
          type: 'doc',
          id: 'plugins/types',
          label: 'Types of Plugins',
        },
        {
          type: 'doc',
          id: 'plugins/logger',
          label: 'Logger',
        },
        {
          type: 'doc',
          id: 'plugins/storage',
          label: 'Storage System',
        },
        {
          type: 'doc',
          id: 'plugins/session',
          label: 'Session Manager',
        },
        {
          type: 'doc',
          id: 'plugins/template-engine',
          label: 'Template Engine',
        },
        {
          type: 'doc',
          id: 'plugins/router',
          label: 'Router',
        },
        {
          type: 'doc',
          id: 'plugins/middleware',
          label: 'Middleware',
        },
        {
          type: 'doc',
          id: 'plugins/routes',
          label: 'Routes',
        },
        {
          type: 'doc',
          id: 'plugins/grants',
          label: 'Grant Requests',
        },
        {
          type: 'doc',
          id: 'plugins/settings',
          label: 'Settings',
        },
        {
          type: 'doc',
          id: 'plugins/assets',
          label: 'Assets',
        },
        {
          type: 'doc',
          id: 'plugins/funcmaps',
          label: 'Funcmaps',
        },
        {
          type: 'doc',
          id: 'plugins/practices',
          label: 'Best Practices & FAQ',
        },
      ],
    },
    {
      type: 'category',
      label: 'CLI',
      items: [
        {
          type: 'doc',
          id: 'cli/amb',
          label: 'Install amb',
        },
        {
          type: 'doc',
          id: 'cli/devconsole',
          label: 'Dev Console',
        },
        {
          type: 'doc',
          id: 'cli/createapp',
          label: 'createapp',
        },
        {
          type: 'doc',
          id: 'cli/enable',
          label: 'enable',
        },
        {
          type: 'doc',
          id: 'cli/grant',
          label: 'grant',
        },
        {
          type: 'doc',
          id: 'cli/encryptstorage',
          label: 'encryptstorage',
        },
        {
          type: 'doc',
          id: 'cli/decryptstorage',
          label: 'decryptstorage',
        },
      ],
    },
    {
      type: 'category',
      label: 'Template',
      items: [
        {
          type: 'doc',
          id: 'template/app',
          label: 'ambient-template',
        },
        {
          type: 'doc',
          id: 'template/autorebuild',
          label: 'Automatic Rebuilds',
        },
        {
          type: 'doc',
          id: 'template/swagger',
          label: 'Swagger Generation',
        },
        {
          type: 'doc',
          id: 'template/settings',
          label: 'App Settings',
        },
      ],
    },
    {
      type: 'doc',
      id: 'faq',
      label: 'FAQ',
    },
  ],
};

module.exports = sidebars;
